// Generates the PWA icon set in `public/icons/` from one of the owner's avatars (#15 Part B).
//
// Run it when the source avatar changes: `node scripts/pwa-icons.mjs [avatar-id]`. The output is committed,
// so a normal build and a normal clone never run this — which is the point: `npm run build` must not depend
// on a browser, and CI's build step does not have one before the Playwright install step.
//
// It renders with the Chromium that `@playwright/test` already brings, rather than an image library. That is
// not cleverness for its own sake: the avatars are `.webp` portraits that the game crops with
// `object-fit: cover; object-position: 50% 30%` (src/style.css), and rendering them through the same CSS is
// the only way to be sure the face in the icon sits where the face in the game sits. It also adds no
// dependency — the allowlist rail in tests/unit/guardrails.test.ts would fail one.
//
// Two purposes, because they are cropped differently and a single file cannot serve both:
//   - `any`      fills the square edge to edge, which is what a browser tab and a desktop shortcut show.
//   - `maskable` is cropped by the platform to a circle, a squircle or a rounded square, so everything that
//     must survive sits inside the centre 80% and the rest is background. An `any` icon declared maskable is
//     the classic mistake: Android crops the ninja's head off.
//
// There is deliberately no splash image. A PWA's splash screen is composed by the platform from `name`,
// `background_color` and the 512px icon in the manifest — shipping a splash asset would be shipping a file
// nothing reads. The Android APK's splash is a different thing and is generated by scripts/android-assets.py.
import { chromium } from '@playwright/test';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);

// The same resolution playwright.config.ts uses, and for the same reason: the cloud container ships Chromium
// at a fixed path and blocks `playwright install`, while a laptop has its own download. Written out rather
// than imported because this is a plain ESM script and the config is TypeScript.
const bundled = '/opt/pw-browsers/chromium';
const executablePath = process.env.PW_CHROMIUM || (existsSync(bundled) ? bundled : undefined);

/** The ground the whole game sits on; the same value as `background_color`/`theme_color` in the manifest. */
export const GROUND = '#131a33';
/** Where the face is, vertically: the `--focus` default in src/style.css. */
export const FOCUS = 0.3;
/** Maskable safe zone: the platform may crop to a circle of 80% of the width, so the art stays inside it. */
export const SAFE = 0.8;

/**
 * The page a single icon is screenshotted from. `size` is both the CSS box and the device pixel count, so
 * one screenshot is exactly one icon with no resampling afterwards.
 */
export function iconPage(src, size, maskable) {
  const inset = maskable ? ((1 - SAFE) / 2) * 100 : 0;
  return `<!doctype html><meta charset="utf-8"><style>
    html,body{margin:0;padding:0}
    .icon{width:${size}px;height:${size}px;background:${GROUND};overflow:hidden;position:relative}
    .icon img{position:absolute;inset:${inset}%;width:${100 - inset * 2}%;height:${100 - inset * 2}%;
      object-fit:cover;object-position:50% ${FOCUS * 100}%}
  </style><div class="icon"><img src="${src}" alt=""></div>`;
}

/**
 * Every icon the manifest declares, and how each is drawn. Keep this and the manifest in step (a rail does).
 *
 * The three the manifest points at are `.webp`, and that is a size decision with a real number behind it: as
 * lossless PNGs the four came to 733 KB, against a `dist/` that was 1.26 MB — a 58% heavier first install,
 * for four pictures of one ninja, on the very feature whose subject is installing and playing offline. Every
 * browser that reads a web app manifest has decoded WebP for years, and the game already ships its whole
 * avatar roster as `.webp`. The Apple icon stays a PNG because Safari never reads the manifest at all: it
 * reads `<link rel="apple-touch-icon">`, and it will not take a WebP there.
 */
export const ICONS = [
  { file: 'icon-192.webp', size: 192, maskable: false },
  { file: 'icon-512.webp', size: 512, maskable: false },
  { file: 'maskable-512.webp', size: 512, maskable: true },
  // iOS does not round the corners of a PNG it is given, so this one is drawn edge to edge like `any`.
  { file: 'apple-touch-icon.png', size: 180, maskable: false },
];

/** Quality for the WebP re-encode. 0.92 is visually lossless on flat art at these sizes and ~6× smaller. */
export const WEBP_QUALITY = 0.92;

/** Re-encode a PNG screenshot as WebP, 1:1, in the page that produced it. */
async function toWebp(page, png, quality = WEBP_QUALITY) {
  const dataUrl = await page.evaluate(async ([b64, q]) => {
    const img = new Image();
    img.src = `data:image/png;base64,${b64}`;
    await img.decode();
    const c = document.createElement('canvas');
    c.width = img.naturalWidth; c.height = img.naturalHeight;
    c.getContext('2d').drawImage(img, 0, 0);
    return c.toDataURL('image/webp', q);
  }, [png.toString('base64'), quality]);
  // A browser that cannot encode WebP answers with a PNG data URL instead of failing, and the file would
  // then be a PNG wearing a .webp name — served with the wrong type and silently 6× the intended size.
  if (!dataUrl.startsWith('data:image/webp;base64,')) throw new Error(`canvas did not encode WebP: ${dataUrl.slice(0, 40)}`);
  return Buffer.from(dataUrl.slice('data:image/webp;base64,'.length), 'base64');
}

async function main() {
  const id = process.argv[2] ?? 'sensei';
  const avatar = new URL(`public/avatars/${id}.webp`, root);
  // Read and inline rather than pointing at the file: `setContent` leaves the page on an `about:blank`
  // origin, which is not allowed to fetch `file://`, and the image would silently never load. Reading it
  // here also fails loudly on a missing avatar instead of screenshotting a broken-image icon.
  const src = `data:image/webp;base64,${readFileSync(avatar).toString('base64')}`;
  const out = new URL('public/icons/', root);
  mkdirSync(fileURLToPath(out), { recursive: true });

  const browser = await chromium.launch(executablePath ? { executablePath } : {});
  try {
    for (const { file, size, maskable } of ICONS) {
      const page = await browser.newPage({ viewport: { width: size, height: size } });
      await page.setContent(iconPage(src, size, maskable));
      const img = page.locator('.icon img');
      await img.waitFor();
      // The screenshot must not race the decode: a .webp that has not painted yields a blank square, and a
      // blank square is a perfectly valid PNG that nothing downstream would question.
      await page.waitForFunction(() => {
        const el = document.querySelector('.icon img');
        return el instanceof HTMLImageElement && el.complete && el.naturalWidth > 0;
      });
      const png = await page.locator('.icon').screenshot();
      // WebP is produced by re-encoding that screenshot through a canvas in the same browser, rather than by
      // drawing the avatar into a canvas directly. Drawing it directly would mean writing the `cover` crop
      // out again in arithmetic, and then the icon would only match the game's CSS for as long as two
      // separate pieces of code agreed. This way the pixels are the ones the browser laid out.
      const bytes = file.endsWith('.webp') ? await toWebp(page, png) : png;
      writeFileSync(fileURLToPath(new URL(file, out)), bytes);
      await page.close();
      console.log(`wrote public/icons/${file} (${size}px${maskable ? ', maskable' : ''}) from ${id}`);
    }
  } finally {
    await browser.close();
  }
}

// Same guard, same fix, same reason as build-sw.mjs and bundle-single.mjs (#116): a raw filesystem path
// compared to a percent-encoded `file://` URL is false the moment the path needs escaping, which silently
// no-ops the icon generation instead of running or erroring.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
